version: '3.9'

services:
  nextjs:
    container_name: nextjs-preview
    restart: always
    command: yarn dev
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    networks:
      default:
        aliases:
          - frontend
        ipv4_address: 172.18.0.6
    ports:
      - 3000:3000
    volumes:
      - .:/app
      - /node_modules
    env_file:
      - ./.env.local

networks:
  default:
    ipam:
      driver: default
      config:
        - subnet: '172.18.0.0/16'

volumes:
  project_development:
  pg_data:
  mongodb_data:
