process.env.VERSION = '1.7.0';
process.env.API_URI = 'http://localhost:4000';
process.env.WEBAPP_URI = 'http://localhost:3000';
process.env.PORT = '4000';
process.env.DATABASE_URL =
  'postgresql://postgres:postgres@postgres/project_development';
process.env.DB_PORT = '5432';
process.env.DB_USERNAME = 'postgres';
process.env.DB_PASSWORD = 'postgres';
process.env.DB_DATABASE_NAME = 'project_development';
process.env.MONGODB_USERNAME = 'mongodb';
process.env.MONGODB_PASSWORD = 'mongodb';
process.env.MONGODB_HOST = 'mongodb';
process.env.MONGODB_PORT = '27017';
process.env.MONGODB_NAME = 'project_development';
process.env.MONGODB_GRIDFS_NAME = 'project_development_gridfs';
process.env.MONGODB_CONNECTION_SSL = 'false';
process.env.MONGODB_PROJECT_NAME = 'niro_health';
process.env.REDIS_HOST = 'redis://redis:6379';
process.env.REDIS_PORT = '6379';
process.env.REDIS_PASSWORD = '';
process.env.BULL_BOARD_USERNAME = 'admin';
process.env.BULL_BOARD_PASSWORD = 'admin';
process.env.CRON_TIMEZONE = 'America/Sao_Paulo';
process.env.CRYPTO_PASSWORD = 'o4t7bNT5CbOnlqBcah40R99zierzSQz3MS9Ssceqq2U=';
process.env.MASTER_KEY =
  'eJwFwcFOwzAMANBviZxTJB+c2Il7q7ZdKGWlbGzqKaKbWihTGYzR3+e9knQFqTI7dB5Hz1FCIacPZ8LdF9S4Ldrwa8wymrt7YcJ60xxlQU25g7+068McmjU6GKw3xMr5RI/gIzz3sorqiA3rTRvGs9JUu9bo6NCifRImwQLVwnhRzSml48OeQecSbPiZM+8OSHotaeFNjgXE6/snyVCj+Sa8nvELJnFyFoC07Muh7LQs4jZRf1vnSLZqJxdu/tLmrj+JrUzwYjmxKV4Rwecgb0gY0z8TjUCv';
process.env.JWT_SECRET = 'cLoM/xpKjQpuL825AZexwyitebaOg94Gr4SzBiBNN6M=';
process.env.COOKIE_SECRET = 'aMIKHAO4USHeyz5b1SqHwKbQcG5ln/D6XkXNqvS8/e0=';
process.env.SESSION_SECRET = 'Hn+s7UQPty8vkUqvuzzmqysSO0LV/P8r8oUMXEbRLKY=';
process.env.AXIOS_URI = 'http://localhost:4000';
process.env.AXIOS_AUTHORIZATION = '3b93157d4096c56fd6e96570b6016b87f6443202';
process.env.AWS_ACCESS_KEY_ID = 'AKIA56N57H7KHQVADY55';
process.env.AWS_SECRET_ACCESS_KEY = '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';
process.env.SMTP_HOST = 'smtp.google.com';
process.env.SMTP_PORT = '587';
process.env.SMTP_SECURE = 'false';
process.env.SMTP_USERNAME = 'jest@gmail.com';
process.env.SMTP_PASSWORD = 'S3nh@Fort3!';
