version: '3.9'

services:
  nestjs:
    container_name: nestjs-produciton
    depends_on:
      - postgres
    command: yarn start:prod
    build:
      context: .
      dockerfile: production.dockerfile
    networks:
      niro-production:
        aliases:
          - backend
        ipv4_address: 172.18.0.2
    ports:
      - ${PORT}:${PORT}
    volumes:
      - niro-production:/app
    env_file:
      - ./.env
  postgres:
    container_name: postgres-produciton
    image: postgres:latest
    networks:
      niro-production:
        aliases:
          - postgres
        ipv4_address: 172.18.0.3
    ports:
      - 5432:5432
    volumes:
      - pg-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      PG_DATA: /var/lib/postgresql/data
  redis:
    container_name: redis-preview
    image: redis:latest
    networks:
      niro_development:
        aliases:
          - redis
        ipv4_address: 172.18.0.4
    ports:
      - 6379:6379
    volumes:
      - niro_development:/data

networks:
  niro-production:
    ipam:
      driver: default
      config:
        - subnet: '172.18.0.0/16'

volumes:
  niro-production:
  pg-data:
