version: '3.9'

services:
  nestjs:
    container_name: nestjs-preview
    depends_on:
      - postgres
    command: yarn start:debug
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      project_development:
        aliases:
          - backend
        ipv4_address: 172.18.0.2
    ports:
      - ${PORT}:${PORT}
    volumes:
      - .:/app
      - ./src/core/libs/locales:/app/dist/core/libs/locales
      - ./src/core/templates:/app/dist/core/templates
      - ./src/core/project.config.json:/app/dist/core/project.config.json
      - project_development:/app/node_modules
    env_file:
      - ./.env
  postgres:
    container_name: postgres-preview
    image: postgres:latest
    restart: always
    networks:
      project_development:
        aliases:
          - postgres
        ipv4_address: 172.18.0.3
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      PG_DATA: /var/lib/postgresql/data
  redis:
    container_name: redis-preview
    image: redis:latest
    restart: always
    networks:
      project_development:
        aliases:
          - redis
        ipv4_address: 172.18.0.4
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    volumes:
      - project_development:/data

networks:
  project_development:
    ipam:
      driver: default
      config:
        - subnet: '172.18.0.0/16'

volumes:
  project_development:
  pg_data:
