version: '3.9'

services:
  postgres:
    container_name: postgres-preview
    image: postgres:latest
    restart: always
    networks:
      project_development:
        aliases:
          - postgres
        ipv4_address: 172.18.0.3
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      PG_DATA: /var/lib/postgresql/data
  mongodb:
    container_name: mongodb-preview
    image: mongo:latest
    restart: always
    networks:
      project_development:
        aliases:
          - mongodb
        ipv4_address: 172.18.0.4
    ports:
      - ${MONGODB_PORT}:${MONGODB_PORT}
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}
  redis:
    container_name: redis-preview
    image: redis:latest
    restart: always
    networks:
      project_development:
        aliases:
          - redis
        ipv4_address: 172.18.0.5
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    volumes:
      - project_development:/data
  nestjs:
    container_name: nestjs-preview
    restart: always
    links:
      - postgres
      - mongodb
      - redis
    depends_on:
      - postgres
      - mongodb
      - redis
    command: yarn start:debug
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    networks:
      project_development:
        aliases:
          - backend
        ipv4_address: 172.18.0.2
    ports:
      - ${PORT}:${PORT}
      - 9229:9229 # Debug port
    volumes:
      - .:/app
      - /node_modules
      - ./src/core/libs/locales:/app/dist/core/libs/locales
      - ./src/core/libs/templates:/app/dist/core/libs/templates
      - ./src/project.config.json:/app/dist/project.config.json
    env_file:
      - ./.env

networks:
  project_development:
    ipam:
      driver: default
      config:
        - subnet: '172.18.0.0/16'

volumes:
  project_development:
  pg_data:
  mongodb_data:
