version: '3.9'

services:
  nestjs:
    container_name: nestjs-preview
    depends_on:
      - postgres
    command: yarn start:debug
    build:
      context: .
      dockerfile: development.dockerfile
    networks:
      niro-development:
        aliases:
          - backend
        ipv4_address: 172.18.0.2
    ports:
      - ${PORT}:${PORT}
    volumes:
      - .:/app
      - ./src/core/locales:/app/dist/core/locales
      - ./src/core/niro.config.json:/app/dist/core/niro.config.json
      - niro-development:/app/node_modules
    env_file:
      - ./.env
  postgres:
    container_name: postgres-preview
    image: postgres:latest
    networks:
      niro-development:
        aliases:
          - postgres
        ipv4_address: 172.18.0.3
    ports:
      - 5432:5432
    volumes:
      - pg-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      PG_DATA: /var/lib/postgresql/data
  redis:
    container_name: redis-preview
    image: redis:latest
    networks:
      niro-development:
        aliases:
          - redis
        ipv4_address: 172.18.0.4
    ports:
      - 6379:6379
    volumes:
      - niro-development:/data

networks:
  niro-development:
    ipam:
      driver: default
      config:
        - subnet: '172.18.0.0/16'

volumes:
  niro-development:
  pg-data:
